#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

# Emit "#define <MACRO>_FONT_ID (<hash>)" from a family's 4 style headers. The id
# is a 32-bit-folded SHA256 of the header contents, so it changes when the font
# data changes (forcing font-map re-registration). Filenames are passed as ARGV
# to avoid shell-quoting the ruby string.
emit_id() {
  local macro="$1" prefix="$2"
  local hash
  hash=$(ruby -rdigest -e 'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' \
    "./${prefix}_regular.h" "./${prefix}_bold.h" "./${prefix}_bolditalic.h" "./${prefix}_italic.h")
  echo "#define ${macro}_FONT_ID (${hash})"
}

# NotoSerif is the built-in serif (reader serif + UI Title/BodyLarge/compact roles).
# Literata 10 is the lone retained Literata face (Body/Caption/Accent roles).
emit_id "LITERATA_10" "literata_10"

for size in 6 8 10 12 14 16 18; do
  emit_id "NOTOSERIF_${size}" "notoserif_${size}"
done

for size in 12 14 16 18; do
  emit_id "NOTOSANS_${size}" "notosans_${size}"
done

# UI_10 / UI_12 are repointed to the active theme's Body/BodyLarge role families
# at runtime (UITheme::repointUiFonts) — their ids are stable handles, not tied to
# a specific face, so they're frozen here (the Ubuntu faces once hashed are gone).
echo "#define UI_10_FONT_ID (22918846)"
echo "#define UI_12_FONT_ID (1635686837)"

# SMALL is the 1-bit NotoSans 8 (single regular face).
echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)' \
  "./notosans_8_regular.h"
))"

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for id in LITERATA_10 \
          NOTOSERIF_6 NOTOSERIF_8 NOTOSERIF_10 NOTOSERIF_12 NOTOSERIF_14 NOTOSERIF_16 NOTOSERIF_18 \
          NOTOSANS_12 NOTOSANS_14 NOTOSANS_16 NOTOSANS_18 \
          UI_10 UI_12 SMALL; do
  echo "static_assert(${id}_FONT_ID != 0, \"Font ID collision with sentinel\");"
done
