#pragma once

#include <builtinFonts/notoserif_5_bold.h>
#include <builtinFonts/notoserif_5_bolditalic.h>
#include <builtinFonts/notoserif_5_italic.h>
#include <builtinFonts/notoserif_5_regular.h>
#include <builtinFonts/notoserif_6_bold.h>
#include <builtinFonts/notoserif_6_bolditalic.h>
#include <builtinFonts/notoserif_6_italic.h>
#include <builtinFonts/notoserif_6_regular.h>
#include <builtinFonts/notoserif_8_bold.h>
#include <builtinFonts/notoserif_8_bolditalic.h>
#include <builtinFonts/notoserif_8_italic.h>
#include <builtinFonts/notoserif_8_regular.h>
#include <builtinFonts/notoserif_10_bold.h>
#include <builtinFonts/notoserif_10_bolditalic.h>
#include <builtinFonts/notoserif_10_italic.h>
#include <builtinFonts/notoserif_10_regular.h>
#include <builtinFonts/notoserif_12_bold.h>
#include <builtinFonts/notoserif_12_bolditalic.h>
#include <builtinFonts/notoserif_12_italic.h>
#include <builtinFonts/notoserif_12_regular.h>
#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/literata_10_bold.h>
#include <builtinFonts/literata_10_bolditalic.h>
#include <builtinFonts/literata_10_italic.h>
#include <builtinFonts/literata_10_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
