#!/usr/bin/env python3
"""Generate C++ theme data structures and JSON parser from YAML schema.

Reads scripts/theme_schema.yaml and generates:
  src/components/themes/ThemeData.generated.h   — enums + ThemeData struct
  src/components/themes/ThemeDefaults.generated.h — Folio default constant
  src/ThemeJsonParser.generated.cpp              — enum tables + field parser

Usage:
  python scripts/gen_theme.py                          # auto-detect paths
  python scripts/gen_theme.py <schema> <output_dir>    # explicit paths
"""

from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

HEADER_COMMENT = "// THIS FILE IS AUTO-GENERATED by gen_theme.py — DO NOT EDIT.\n"
CLANG_FORMAT_OFF = "// clang-format off\n"
CLANG_FORMAT_ON = "// clang-format on\n"

PRIMITIVE_TYPES = {"int", "bool", "float"}


# ---------------------------------------------------------------------------
# Schema helpers
# ---------------------------------------------------------------------------

def load_schema(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def is_group(entry: dict) -> bool:
    return "group" in entry


def is_field(entry: dict) -> bool:
    return "cpp" in entry and "group" not in entry


def field_json_key(field: dict) -> str:
    return field.get("json", field["cpp"])


def is_enum_type(type_name: str, schema: dict) -> bool:
    return type_name in schema.get("enums", {})


def is_external_type(type_name: str, schema: dict) -> bool:
    return type_name in schema.get("external_types", {})


def is_parseable_type(type_name: str, schema: dict) -> bool:
    return type_name in PRIMITIVE_TYPES or is_enum_type(type_name, schema) or is_external_type(type_name, schema)


def enum_table_name(enum_name: str) -> str:
    return f"k{enum_name}s"


def get_table_name(type_name: str, schema: dict) -> str:
    if is_enum_type(type_name, schema):
        return enum_table_name(type_name)
    ext = schema["external_types"].get(type_name)
    if ext:
        return ext["table_name"]
    raise ValueError(f"No table for type: {type_name}")


def cpp_type_str(type_name: str) -> str:
    """Return the C++ type string for a schema type."""
    if type_name in PRIMITIVE_TYPES:
        return type_name
    return type_name


def format_default(val: Any, type_name: str) -> str:
    """Format a default value for C++ designated initializer."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, str):
        return val
    return str(val)


def short_alias(group_name: str) -> str:
    """Generate a short ArduinoJson variable alias from a group name."""
    aliases = {
        "header": "hdr",
        "selection": "sel",
        "cover": "cov",
        "list": "lst",
        "layout": "lay",
        "battery": "bat",
        "buttonHints": "bh",
        "tabBar": "tb",
        "scrollBar": "sb",
        "home": "hm",
        "progressBar": "pb",
        "statusBar": "stb",
        "keyboard": "kb",
        "popup": "pp",
        "textField": "tf",
        "progress": "prog",
    }
    return aliases.get(group_name, group_name[:3])


# ---------------------------------------------------------------------------
# ThemeData.generated.h
# ---------------------------------------------------------------------------

def generate_header(schema: dict) -> str:
    lines: list[str] = []
    lines.append("#pragma once\n")
    lines.append(HEADER_COMMENT)
    lines.append(CLANG_FORMAT_OFF)
    lines.append("\n")

    # Collect includes for external types
    includes: set[str] = set()
    for ext in schema.get("external_types", {}).values():
        includes.add(ext["include"])
    lines.append("#include <cstdint>\n")
    for inc in sorted(includes):
        if inc.startswith("<"):
            lines.append(f"#include {inc}\n")
        else:
            lines.append(f"#include {inc}\n")
    lines.append("\n")

    # Enum definitions
    for enum_name, variants in schema.get("enums", {}).items():
        lines.append(f"enum class {enum_name} : uint8_t {{\n")
        for v in variants:
            lines.append(f"  {v['name']},\n")
        lines.append("};\n\n")

    # ThemeData struct
    lines.append("struct ThemeData {\n")
    lines.append("  // id and Fonts are hand-written in ThemeData.h\n")
    lines.append("  const char* id;\n")
    lines.append("\n")
    lines.append("  struct Fonts {\n")
    lines.append("    int titleId;\n")
    lines.append("    int headingId;\n")
    lines.append("    int bodyId;\n")
    lines.append("    int captionId;\n")
    lines.append("    int accentId;\n")
    lines.append("    int bodyIdCompact;\n")
    lines.append("    int captionIdCompact;\n")
    lines.append("    int accentIdCompact;\n")
    lines.append("  } fonts;\n")
    lines.append("\n")

    for entry in schema["struct"]:
        if is_group(entry):
            _emit_struct_group(lines, entry, schema, indent=2)
        elif is_field(entry):
            t = cpp_type_str(entry["type"])
            lines.append(f"  {t} {entry['cpp']};\n")

    lines.append("};\n")
    lines.append("\n")
    lines.append(CLANG_FORMAT_ON)
    return "".join(lines)


def _emit_struct_group(lines: list[str], group: dict, schema: dict, indent: int) -> None:
    pad = " " * indent
    struct_name = group.get("struct_name", group["group"].title())
    member_name = group["group"]
    lines.append(f"{pad}struct {struct_name} {{\n")
    for field in group.get("fields", []):
        t = cpp_type_str(field["type"])
        lines.append(f"{pad}  {t} {field['cpp']};\n")
    for child in group.get("children", []):
        _emit_struct_group(lines, child, schema, indent + 2)
    lines.append(f"{pad}}} {member_name};\n\n")


# ---------------------------------------------------------------------------
# ThemeDefaults.generated.h
# ---------------------------------------------------------------------------

def generate_defaults(schema: dict) -> str:
    lines: list[str] = []
    lines.append("#pragma once\n")
    lines.append(HEADER_COMMENT)
    lines.append(CLANG_FORMAT_OFF)
    lines.append("\n")
    lines.append('#include "ThemeData.generated.h"\n')
    lines.append("\n")
    lines.append("namespace BuiltinThemes {\n\n")
    lines.append("inline constexpr ThemeData FolioDefaults = {\n")
    lines.append("    .id = nullptr,\n")
    lines.append("    .fonts = {},\n")

    for entry in schema["struct"]:
        if is_group(entry):
            _emit_default_group(lines, entry, schema, indent=4)
        elif is_field(entry):
            val = format_default(entry["default"], entry["type"])
            lines.append(f"    .{entry['cpp']} = {val},\n")

    lines.append("};\n\n")
    lines.append("}  // namespace BuiltinThemes\n")
    lines.append("\n")
    lines.append(CLANG_FORMAT_ON)
    return "".join(lines)


def _emit_default_group(lines: list[str], group: dict, schema: dict, indent: int) -> None:
    pad = " " * indent
    member = group["group"]
    lines.append(f"{pad}.{member} = {{\n")
    for field in group.get("fields", []):
        val = format_default(field["default"], field["type"])
        lines.append(f"{pad}    .{field['cpp']} = {val},\n")
    for child in group.get("children", []):
        _emit_default_group(lines, child, schema, indent + 4)
    lines.append(f"{pad}}},\n")


# ---------------------------------------------------------------------------
# ThemeJsonParser.generated.cpp
# ---------------------------------------------------------------------------

def generate_parser(schema: dict) -> str:
    lines: list[str] = []
    lines.append(HEADER_COMMENT)
    lines.append(CLANG_FORMAT_OFF)
    lines.append("\n")
    lines.append("#include <ArduinoJson.h>\n")
    lines.append("\n")
    lines.append("#include <cstring>\n")
    lines.append("\n")
    lines.append('#include "components/themes/ThemeData.h"\n')
    lines.append("\n")

    # EnumEntry struct + parseEnum template
    lines.append("namespace {\n\n")
    lines.append("struct EnumEntry {\n")
    lines.append("  const char* name;\n")
    lines.append("  uint8_t value;\n")
    lines.append("};\n\n")

    lines.append("template <typename E, size_t N>\n")
    lines.append("E parseEnum(const char* str, const EnumEntry (&table)[N], E fallback) {\n")
    lines.append("  if (!str) return fallback;\n")
    lines.append("  for (const auto& e : table) {\n")
    lines.append("    if (strcmp(str, e.name) == 0) return static_cast<E>(e.value);\n")
    lines.append("  }\n")
    lines.append("  return fallback;\n")
    lines.append("}\n\n")

    # Project enum tables
    for enum_name, variants in schema.get("enums", {}).items():
        table = enum_table_name(enum_name)
        lines.append(f"constexpr EnumEntry {table}[] = {{\n")
        for v in variants:
            lines.append(f'    {{"{v["json"]}", static_cast<uint8_t>({enum_name}::{v["name"]})}},\n')
        lines.append("};\n\n")

    # External type tables
    for type_name, ext in schema.get("external_types", {}).items():
        table = ext["table_name"]
        lines.append(f"constexpr EnumEntry {table}[] = {{\n")
        for v in ext["variants"]:
            lines.append(f'    {{"{v["json"]}", static_cast<uint8_t>({v["cpp"]})}},\n')
        lines.append("};\n\n")

    lines.append("}  // namespace\n\n")

    # parseThemeFields function
    lines.append("void parseThemeFields(JsonDocument& doc, ThemeData& out) {\n")

    for entry in schema["struct"]:
        if is_group(entry):
            _emit_parser_group(lines, entry, schema, parent_var="doc", access_prefix="out", indent=2)
        elif is_field(entry):
            _emit_parser_field(lines, entry, schema, obj_var="doc", access_prefix="out", indent=2)

    lines.append("}\n")
    lines.append("\n")
    lines.append(CLANG_FORMAT_ON)
    return "".join(lines)


def _emit_parser_group(
    lines: list[str],
    group: dict,
    schema: dict,
    parent_var: str,
    access_prefix: str,
    indent: int,
) -> None:
    pad = " " * indent
    member = group["group"]
    json_key = group.get("json", member)
    alias = short_alias(member)
    member_path = f"{access_prefix}.{member}"

    lines.append(f"{pad}JsonObjectConst {alias} = {parent_var}[\"{json_key}\"];\n")
    lines.append(f"{pad}if (!{alias}.isNull()) {{\n")

    for field in group.get("fields", []):
        _emit_parser_field(lines, field, schema, obj_var=alias, access_prefix=member_path, indent=indent + 2)

    for child in group.get("children", []):
        _emit_parser_group(lines, child, schema, parent_var=alias, access_prefix=member_path, indent=indent + 2)

    lines.append(f"{pad}}}\n\n")


def _emit_parser_field(
    lines: list[str],
    field: dict,
    schema: dict,
    obj_var: str,
    access_prefix: str,
    indent: int,
) -> None:
    pad = " " * indent
    cpp = field["cpp"]
    json_key = field_json_key(field)
    type_name = field["type"]
    target = f"{access_prefix}.{cpp}"

    if type_name in PRIMITIVE_TYPES:
        lines.append(f'{pad}{target} = {obj_var}["{json_key}"] | {target};\n')
    elif is_enum_type(type_name, schema) or is_external_type(type_name, schema):
        table = get_table_name(type_name, schema)
        lines.append(
            f'{pad}{target} = parseEnum({obj_var}["{json_key}"]'
            f" | static_cast<const char*>(nullptr),\n"
            f"{pad}    {table}, {target});\n"
        )


# ---------------------------------------------------------------------------
# File writing (only when content changed)
# ---------------------------------------------------------------------------

def write_if_changed(path: str, content: str) -> bool:
    new_hash = hashlib.sha256(content.encode()).hexdigest()
    if os.path.exists(path):
        with open(path) as f:
            old_hash = hashlib.sha256(f.read().encode()).hexdigest()
        if old_hash == new_hash:
            return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(schema_path: str | None = None, output_root: str | None = None) -> None:
    if schema_path is None:
        script_dir = Path(__file__).resolve().parent
        schema_path = str(script_dir / "theme_schema.yaml")
    if output_root is None:
        output_root = str(Path(schema_path).resolve().parent.parent)

    schema = load_schema(schema_path)

    header_path = os.path.join(output_root, "src", "components", "themes", "ThemeData.generated.h")
    defaults_path = os.path.join(output_root, "src", "components", "themes", "ThemeDefaults.generated.h")
    parser_path = os.path.join(output_root, "src", "ThemeJsonParser.generated.cpp")

    header_content = generate_header(schema)
    defaults_content = generate_defaults(schema)
    parser_content = generate_parser(schema)

    changed = False
    if write_if_changed(header_path, header_content):
        print(f"gen_theme: wrote {header_path}")
        changed = True
    if write_if_changed(defaults_path, defaults_content):
        print(f"gen_theme: wrote {defaults_path}")
        changed = True
    if write_if_changed(parser_path, parser_content):
        print(f"gen_theme: wrote {parser_path}")
        changed = True
    if not changed:
        print("gen_theme: all outputs up to date")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("schema", nargs="?", help="Path to theme_schema.yaml")
    parser.add_argument("output_root", nargs="?", help="Project root directory")
    args = parser.parse_args()
    main(args.schema, args.output_root)
else:
    try:
        Import("env")  # type: ignore[name-defined]  # noqa: F821 — SCons global
        main()
    except NameError:
        pass
