// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define LITERATA_5_FONT_ID (200942180)
#define LITERATA_6_FONT_ID (350559456)
#define LITERATA_8_FONT_ID (-1818530484)
#define LITERATA_10_FONT_ID (182386865)
#define LITERATA_12_FONT_ID (990915594)
#define LITERATA_14_FONT_ID (1370590625)
#define LITERATA_16_FONT_ID (-1936280279)
#define LITERATA_18_FONT_ID (-817757966)
#define NOTOSANS_12_FONT_ID (1596976206)
#define NOTOSANS_14_FONT_ID (1803284322)
#define NOTOSANS_16_FONT_ID (-947881680)
#define NOTOSANS_18_FONT_ID (707992787)
#define UI_10_FONT_ID (22918846)
#define UI_12_FONT_ID (1635686837)
#define SMALL_FONT_ID (-835447633)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LITERATA_5_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_6_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_8_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LITERATA_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
