// THIS FILE IS AUTO-GENERATED by gen_theme.py — DO NOT EDIT.
// clang-format off

#include <ArduinoJson.h>

#include <cstring>

#include "components/themes/ThemeData.h"

namespace {

struct EnumEntry {
  const char* name;
  uint8_t value;
};

template <typename E, size_t N>
E parseEnum(const char* str, const EnumEntry (&table)[N], E fallback) {
  if (!str) return fallback;
  for (const auto& e : table) {
    if (strcmp(str, e.name) == 0) return static_cast<E>(e.value);
  }
  return fallback;
}

constexpr EnumEntry kHeaderStyles[] = {
    {"centered-title", static_cast<uint8_t>(HeaderStyle::CenteredTitle)},
    {"left-aligned-with-rule", static_cast<uint8_t>(HeaderStyle::LeftAlignedWithRule)},
    {"left-aligned-bordered", static_cast<uint8_t>(HeaderStyle::LeftAlignedBordered)},
    {"left-aligned-plain", static_cast<uint8_t>(HeaderStyle::LeftAlignedPlain)},
};

constexpr EnumEntry kSelectionStyles[] = {
    {"solid-fill", static_cast<uint8_t>(SelectionStyle::SolidFill)},
    {"rounded-fill", static_cast<uint8_t>(SelectionStyle::RoundedFill)},
    {"rounded-row-always", static_cast<uint8_t>(SelectionStyle::RoundedRowAlways)},
    {"layered-frame", static_cast<uint8_t>(SelectionStyle::LayeredFrame)},
};

constexpr EnumEntry kCoverStyles[] = {
    {"default", static_cast<uint8_t>(CoverStyle::Default)},
    {"card", static_cast<uint8_t>(CoverStyle::Card)},
    {"card-rounded", static_cast<uint8_t>(CoverStyle::CardRounded)},
};

constexpr EnumEntry kButtonHintsStyles[] = {
    {"boxed", static_cast<uint8_t>(ButtonHintsStyle::Boxed)},
    {"hairline", static_cast<uint8_t>(ButtonHintsStyle::Hairline)},
    {"rounded-filled", static_cast<uint8_t>(ButtonHintsStyle::RoundedFilled)},
    {"paired-groups", static_cast<uint8_t>(ButtonHintsStyle::PairedGroups)},
};

constexpr EnumEntry kSideButtonHintsStyles[] = {
    {"sharp", static_cast<uint8_t>(SideButtonHintsStyle::Sharp)},
    {"rounded", static_cast<uint8_t>(SideButtonHintsStyle::Rounded)},
};

constexpr EnumEntry kTabBarStyles[] = {
    {"underline", static_cast<uint8_t>(TabBarStyle::Underline)},
    {"dithered-rounded", static_cast<uint8_t>(TabBarStyle::DitheredRounded)},
    {"slot-rounded", static_cast<uint8_t>(TabBarStyle::SlotRounded)},
};

constexpr EnumEntry kScrollIndicatorStyles[] = {
    {"arrows", static_cast<uint8_t>(ScrollIndicatorStyle::Arrows)},
    {"thumb", static_cast<uint8_t>(ScrollIndicatorStyle::Thumb)},
    {"line-thumb", static_cast<uint8_t>(ScrollIndicatorStyle::LineThumb)},
};

constexpr EnumEntry kBatteryStyles[] = {
    {"solid", static_cast<uint8_t>(BatteryStyle::Solid)},
    {"segmented", static_cast<uint8_t>(BatteryStyle::Segmented)},
};

constexpr EnumEntry kIndicatorShapes[] = {
    {"circle", static_cast<uint8_t>(IndicatorShape::Circle)},
    {"square", static_cast<uint8_t>(IndicatorShape::Square)},
    {"rounded-rect", static_cast<uint8_t>(IndicatorShape::RoundedRect)},
};

constexpr EnumEntry kPopupMenuSelectionStyles[] = {
    {"solid-fill", static_cast<uint8_t>(PopupMenuSelectionStyle::SolidFill)},
    {"rounded-fill", static_cast<uint8_t>(PopupMenuSelectionStyle::RoundedFill)},
    {"border-only", static_cast<uint8_t>(PopupMenuSelectionStyle::BorderOnly)},
};

constexpr EnumEntry kColors[] = {
    {"clear", static_cast<uint8_t>(Color::Clear)},
    {"white", static_cast<uint8_t>(Color::White)},
    {"lightgray", static_cast<uint8_t>(Color::LightGray)},
    {"darkgray", static_cast<uint8_t>(Color::DarkGray)},
    {"black", static_cast<uint8_t>(Color::Black)},
};

constexpr EnumEntry kFontStyles[] = {
    {"regular", static_cast<uint8_t>(EpdFontFamily::REGULAR)},
    {"bold", static_cast<uint8_t>(EpdFontFamily::BOLD)},
    {"italic", static_cast<uint8_t>(EpdFontFamily::ITALIC)},
    {"bold-italic", static_cast<uint8_t>(EpdFontFamily::BOLD_ITALIC)},
};

constexpr EnumEntry kFontRoleStyles[] = {
    {"title", static_cast<uint8_t>(FontRole::Title)},
    {"heading", static_cast<uint8_t>(FontRole::Heading)},
    {"body", static_cast<uint8_t>(FontRole::Body)},
    {"caption", static_cast<uint8_t>(FontRole::Caption)},
    {"accent", static_cast<uint8_t>(FontRole::Accent)},
    {"body-compact", static_cast<uint8_t>(FontRole::BodyCompact)},
    {"caption-compact", static_cast<uint8_t>(FontRole::CaptionCompact)},
    {"accent-compact", static_cast<uint8_t>(FontRole::AccentCompact)},
};

}  // namespace

void parseThemeFields(JsonDocument& doc, ThemeData& out) {
  JsonObjectConst hdr = doc["header"];
  if (!hdr.isNull()) {
    out.header.style = parseEnum(hdr["style"] | static_cast<const char*>(nullptr),
        kHeaderStyles, out.header.style);
    out.header.titleStyle = parseEnum(hdr["titleStyle"] | static_cast<const char*>(nullptr),
        kFontStyles, out.header.titleStyle);
    out.header.subtitleStyle = parseEnum(hdr["subtitleStyle"] | static_cast<const char*>(nullptr),
        kFontStyles, out.header.subtitleStyle);
    out.header.bottomBorderHeight = hdr["bottomBorderHeight"] | out.header.bottomBorderHeight;
    out.header.height = hdr["height"] | out.header.height;
    out.header.fontRole = parseEnum(hdr["fontRole"] | static_cast<const char*>(nullptr),
        kFontRoleStyles, out.header.fontRole);
    out.header.titlePrepend = hdr["titlePrepend"] | out.header.titlePrepend.c_str();
    out.header.titleAppend = hdr["titleAppend"] | out.header.titleAppend.c_str();
  }

  JsonObjectConst sel = doc["selection"];
  if (!sel.isNull()) {
    out.selection.style = parseEnum(sel["style"] | static_cast<const char*>(nullptr),
        kSelectionStyles, out.selection.style);
    out.selection.cornerRadius = sel["cornerRadius"] | out.selection.cornerRadius;
    out.selection.textInverted = sel["textInverted"] | out.selection.textInverted;
  }

  JsonObjectConst cov = doc["cover"];
  if (!cov.isNull()) {
    out.cover.style = parseEnum(cov["style"] | static_cast<const char*>(nullptr),
        kCoverStyles, out.cover.style);
    out.cover.cornerRadius = cov["cornerRadius"] | out.cover.cornerRadius;
  }

  JsonObjectConst lst = doc["list"];
  if (!lst.isNull()) {
    out.list.subtitleStyle = parseEnum(lst["subtitleStyle"] | static_cast<const char*>(nullptr),
        kFontStyles, out.list.subtitleStyle);
    out.list.buttonMenuLabelStyle = parseEnum(lst["buttonMenuLabelStyle"] | static_cast<const char*>(nullptr),
        kFontStyles, out.list.buttonMenuLabelStyle);
    out.list.rowHeight = lst["rowHeight"] | out.list.rowHeight;
    out.list.rowHeightWithSubtitle = lst["rowHeightWithSubtitle"] | out.list.rowHeightWithSubtitle;
    out.list.menuRowHeight = lst["menuRowHeight"] | out.list.menuRowHeight;
    out.list.menuSpacing = lst["menuSpacing"] | out.list.menuSpacing;
    out.list.selectionStyle = parseEnum(lst["selectionStyle"] | static_cast<const char*>(nullptr),
        kSelectionStyles, out.list.selectionStyle);
    out.list.showDividers = lst["showDividers"] | out.list.showDividers;
  }

  out.buttonHintsStyle = parseEnum(doc["buttonHintsStyle"] | static_cast<const char*>(nullptr),
      kButtonHintsStyles, out.buttonHintsStyle);
  out.sideButtonHintsStyle = parseEnum(doc["sideButtonHintsStyle"] | static_cast<const char*>(nullptr),
      kSideButtonHintsStyles, out.sideButtonHintsStyle);
  out.scrollIndicatorStyle = parseEnum(doc["scrollIndicatorStyle"] | static_cast<const char*>(nullptr),
      kScrollIndicatorStyles, out.scrollIndicatorStyle);
  out.batteryStyle = parseEnum(doc["batteryStyle"] | static_cast<const char*>(nullptr),
      kBatteryStyles, out.batteryStyle);
  JsonObjectConst lay = doc["layout"];
  if (!lay.isNull()) {
    out.layout.topPadding = lay["topPadding"] | out.layout.topPadding;
    out.layout.verticalSpacing = lay["verticalSpacing"] | out.layout.verticalSpacing;
    out.layout.contentSidePadding = lay["contentSidePadding"] | out.layout.contentSidePadding;
  }

  JsonObjectConst bat = doc["battery"];
  if (!bat.isNull()) {
    out.battery.width = bat["width"] | out.battery.width;
    out.battery.height = bat["height"] | out.battery.height;
    out.battery.barHeight = bat["barHeight"] | out.battery.barHeight;
  }

  JsonObjectConst bh = doc["buttonHints"];
  if (!bh.isNull()) {
    out.buttonHints.height = bh["height"] | out.buttonHints.height;
    out.buttonHints.sideWidth = bh["sideWidth"] | out.buttonHints.sideWidth;
  }

  JsonObjectConst fon = doc["fontPreview"];
  if (!fon.isNull()) {
    out.fontPreview.padding = fon["padding"] | out.fontPreview.padding;
    out.fontPreview.heightPercent = fon["heightPercent"] | out.fontPreview.heightPercent;
  }

  JsonObjectConst tb = doc["tabBar"];
  if (!tb.isNull()) {
    out.tabBar.spacing = tb["spacing"] | out.tabBar.spacing;
    out.tabBar.height = tb["height"] | out.tabBar.height;
    out.tabBar.style = parseEnum(tb["style"] | static_cast<const char*>(nullptr),
        kTabBarStyles, out.tabBar.style);
    out.tabBar.fontRole = parseEnum(tb["fontRole"] | static_cast<const char*>(nullptr),
        kFontRoleStyles, out.tabBar.fontRole);
  }

  JsonObjectConst sb = doc["scrollBar"];
  if (!sb.isNull()) {
    out.scrollBar.width = sb["width"] | out.scrollBar.width;
    out.scrollBar.rightOffset = sb["rightOffset"] | out.scrollBar.rightOffset;
  }

  JsonObjectConst pb = doc["progressBar"];
  if (!pb.isNull()) {
    out.progressBar.height = pb["height"] | out.progressBar.height;
    out.progressBar.marginTop = pb["marginTop"] | out.progressBar.marginTop;
  }

  JsonObjectConst stb = doc["statusBar"];
  if (!stb.isNull()) {
    out.statusBar.horizontalMargin = stb["horizontalMargin"] | out.statusBar.horizontalMargin;
    out.statusBar.verticalMargin = stb["verticalMargin"] | out.statusBar.verticalMargin;
  }

  JsonObjectConst kb = doc["keyboard"];
  if (!kb.isNull()) {
    out.keyboard.keyWidth = kb["keyWidth"] | out.keyboard.keyWidth;
    out.keyboard.keyHeight = kb["keyHeight"] | out.keyboard.keyHeight;
    out.keyboard.keySpacing = kb["keySpacing"] | out.keyboard.keySpacing;
    out.keyboard.bottomKeyHeight = kb["bottomKeyHeight"] | out.keyboard.bottomKeyHeight;
    out.keyboard.bottomKeySpacing = kb["bottomKeySpacing"] | out.keyboard.bottomKeySpacing;
    out.keyboard.bottomAligned = kb["bottomAligned"] | out.keyboard.bottomAligned;
    out.keyboard.centeredText = kb["centeredText"] | out.keyboard.centeredText;
    out.keyboard.verticalOffset = kb["verticalOffset"] | out.keyboard.verticalOffset;
    out.keyboard.textFieldWidthPercent = kb["textFieldWidthPercent"] | out.keyboard.textFieldWidthPercent;
    out.keyboard.widthPercent = kb["widthPercent"] | out.keyboard.widthPercent;
    out.keyboard.keyCornerRadius = kb["keyCornerRadius"] | out.keyboard.keyCornerRadius;
    out.keyboard.fillUnselected = kb["fillUnselected"] | out.keyboard.fillUnselected;
    out.keyboard.outlineAllUnselected = kb["outlineAllUnselected"] | out.keyboard.outlineAllUnselected;
    out.keyboard.drawSpecialOutlineWhenUnselected = kb["drawSpecialOutlineWhenUnselected"] | out.keyboard.drawSpecialOutlineWhenUnselected;
    out.keyboard.secondaryLabelRightPadding = kb["secondaryLabelRightPadding"] | out.keyboard.secondaryLabelRightPadding;
    out.keyboard.secondaryLabelTopPadding = kb["secondaryLabelTopPadding"] | out.keyboard.secondaryLabelTopPadding;
    out.keyboard.minArrowHeadSize = kb["minArrowHeadSize"] | out.keyboard.minArrowHeadSize;
  }

  JsonObjectConst lib = doc["library"];
  if (!lib.isNull()) {
    out.library.pageIndicatorShape = parseEnum(lib["pageIndicatorShape"] | static_cast<const char*>(nullptr),
        kIndicatorShapes, out.library.pageIndicatorShape);
    out.library.pageIndicatorSize = lib["pageIndicatorSize"] | out.library.pageIndicatorSize;
    out.library.pageIndicatorBorder = parseEnum(lib["pageIndicatorBorder"] | static_cast<const char*>(nullptr),
        kColors, out.library.pageIndicatorBorder);
    out.library.pageIndicatorBorderSelected = parseEnum(lib["pageIndicatorBorderSelected"] | static_cast<const char*>(nullptr),
        kColors, out.library.pageIndicatorBorderSelected);
    out.library.pageIndicatorFill = parseEnum(lib["pageIndicatorFill"] | static_cast<const char*>(nullptr),
        kColors, out.library.pageIndicatorFill);
    out.library.pageIndicatorFillSelected = parseEnum(lib["pageIndicatorFillSelected"] | static_cast<const char*>(nullptr),
        kColors, out.library.pageIndicatorFillSelected);
    out.library.pageIndicatorCornerRadius = lib["pageIndicatorCornerRadius"] | out.library.pageIndicatorCornerRadius;
    out.library.pageIndicatorGap = lib["pageIndicatorGap"] | out.library.pageIndicatorGap;
    out.library.coverBorderRadius = lib["coverBorderRadius"] | out.library.coverBorderRadius;
    out.library.coverBorderWidth = lib["coverBorderWidth"] | out.library.coverBorderWidth;
    out.library.coverDropShadowOffsetX = lib["coverDropShadowOffsetX"] | out.library.coverDropShadowOffsetX;
    out.library.coverDropShadowOffsetY = lib["coverDropShadowOffsetY"] | out.library.coverDropShadowOffsetY;
    out.library.pagePaddingX = lib["pagePaddingX"] | out.library.pagePaddingX;
    out.library.pagePaddingY = lib["pagePaddingY"] | out.library.pagePaddingY;
  }

  JsonObjectConst pp = doc["popup"];
  if (!pp.isNull()) {
    out.popup.topOffsetRatio = pp["topOffsetRatio"] | out.popup.topOffsetRatio;
    out.popup.marginX = pp["marginX"] | out.popup.marginX;
    out.popup.marginY = pp["marginY"] | out.popup.marginY;
    out.popup.frameThickness = pp["frameThickness"] | out.popup.frameThickness;
    out.popup.cornerRadius = pp["cornerRadius"] | out.popup.cornerRadius;
    out.popup.textBold = pp["textBold"] | out.popup.textBold;
    out.popup.textInverted = pp["textInverted"] | out.popup.textInverted;
    out.popup.textBaselineOffsetY = pp["textBaselineOffsetY"] | out.popup.textBaselineOffsetY;
    JsonObjectConst prog = pp["progress"];
    if (!prog.isNull()) {
      out.popup.progress.barHeight = prog["barHeight"] | out.popup.progress.barHeight;
      out.popup.progress.drawOutline = prog["drawOutline"] | out.popup.progress.drawOutline;
      out.popup.progress.clampPercent = prog["clampPercent"] | out.popup.progress.clampPercent;
      out.popup.progress.fillInverted = prog["fillInverted"] | out.popup.progress.fillInverted;
      out.popup.progress.outlineInverted = prog["outlineInverted"] | out.popup.progress.outlineInverted;
    }

  }

  JsonObjectConst pop = doc["popupMenu"];
  if (!pop.isNull()) {
    out.popupMenu.rowHeight = pop["rowHeight"] | out.popupMenu.rowHeight;
    out.popupMenu.borderThickness = pop["borderThickness"] | out.popupMenu.borderThickness;
    out.popupMenu.cornerRadius = pop["cornerRadius"] | out.popupMenu.cornerRadius;
    out.popupMenu.shadowOffsetX = pop["shadowOffsetX"] | out.popupMenu.shadowOffsetX;
    out.popupMenu.shadowOffsetY = pop["shadowOffsetY"] | out.popupMenu.shadowOffsetY;
    out.popupMenu.paddingX = pop["paddingX"] | out.popupMenu.paddingX;
    out.popupMenu.panelGap = pop["panelGap"] | out.popupMenu.panelGap;
    out.popupMenu.selectionStyle = parseEnum(pop["selectionStyle"] | static_cast<const char*>(nullptr),
        kPopupMenuSelectionStyles, out.popupMenu.selectionStyle);
    out.popupMenu.selectionCornerRadius = pop["selectionCornerRadius"] | out.popupMenu.selectionCornerRadius;
    out.popupMenu.selectionTextInverted = pop["selectionTextInverted"] | out.popupMenu.selectionTextInverted;
    out.popupMenu.subPanelMutedFill = pop["subPanelMutedFill"] | out.popupMenu.subPanelMutedFill;
    out.popupMenu.fontRole = parseEnum(pop["fontRole"] | static_cast<const char*>(nullptr),
        kFontRoleStyles, out.popupMenu.fontRole);
  }

  JsonObjectConst tf = doc["textField"];
  if (!tf.isNull()) {
    out.textField.horizontalPadding = tf["horizontalPadding"] | out.textField.horizontalPadding;
    out.textField.normalThickness = tf["normalThickness"] | out.textField.normalThickness;
    out.textField.cursorThickness = tf["cursorThickness"] | out.textField.cursorThickness;
    out.textField.lineEndOffset = tf["lineEndOffset"] | out.textField.lineEndOffset;
  }

  JsonObjectConst glo = doc["globalMenu"];
  if (!glo.isNull()) {
    out.globalMenu.paddingX = glo["paddingX"] | out.globalMenu.paddingX;
    out.globalMenu.paddingY = glo["paddingY"] | out.globalMenu.paddingY;
    out.globalMenu.cornerRadius = glo["cornerRadius"] | out.globalMenu.cornerRadius;
    out.globalMenu.borderWidth = glo["borderWidth"] | out.globalMenu.borderWidth;
    out.globalMenu.shadowOffsetX = glo["shadowOffsetX"] | out.globalMenu.shadowOffsetX;
    out.globalMenu.shadowOffsetY = glo["shadowOffsetY"] | out.globalMenu.shadowOffsetY;
    out.globalMenu.popupGap = glo["popupGap"] | out.globalMenu.popupGap;
    out.globalMenu.selectionPadding = glo["selectionPadding"] | out.globalMenu.selectionPadding;
    out.globalMenu.selectionCornerRadius = glo["selectionCornerRadius"] | out.globalMenu.selectionCornerRadius;
    out.globalMenu.selectionFill = parseEnum(glo["selectionFill"] | static_cast<const char*>(nullptr),
        kColors, out.globalMenu.selectionFill);
    out.globalMenu.selectionBorderWidth = glo["selectionBorderWidth"] | out.globalMenu.selectionBorderWidth;
  }

  out.showsFileIcons = doc["showsFileIcons"] | out.showsFileIcons;
}

// clang-format on
